/** @type {import('tailwindcss').Config} */
export default {
  // Theme switching is done via data-theme attribute + CSS custom properties.
  // We do NOT use Tailwind's darkMode: 'class' because all colors are now
  // driven by CSS variables — switching themes just changes variable values.
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── All colors are now CSS custom properties ──────────────────────
        // The hex values below are NEVER used directly — they're just fallbacks.
        // Actual values come from var(--color-*) in index.css, driven by data-theme.
        'surface':                   'var(--color-surface)',
        'surface-dim':               'var(--color-surface-dim)',
        'surface-bright':            'var(--color-surface-bright)',
        'surface-container-lowest':  'var(--color-surface-container-lowest)',
        'surface-container-low':     'var(--color-surface-container-low)',
        'surface-container':         'var(--color-surface-container)',
        'surface-container-high':    'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface':                'var(--color-on-surface)',
        'on-surface-variant':        'var(--color-on-surface-variant)',
        'inverse-surface':           'var(--color-inverse-surface)',
        'inverse-on-surface':        'var(--color-inverse-on-surface)',
        'outline':                   'var(--color-outline)',
        'outline-variant':           'var(--color-outline-variant)',
        'surface-tint':              'var(--color-surface-tint)',
        'primary':                   'var(--color-primary)',
        'on-primary':                'var(--color-on-primary)',
        'primary-container':         'var(--color-primary-container)',
        'on-primary-container':      'var(--color-on-primary-container)',
        'inverse-primary':           'var(--color-inverse-primary)',
        'secondary':                 'var(--color-secondary)',
        'on-secondary':              'var(--color-on-secondary)',
        'secondary-container':       'var(--color-secondary-container)',
        'on-secondary-container':    'var(--color-on-secondary-container)',
        'secondary-fixed':           'var(--color-secondary-fixed)',
        'tertiary':                  'var(--color-tertiary)',
        'on-tertiary':               'var(--color-on-tertiary)',
        'tertiary-container':        'var(--color-tertiary-container)',
        'on-tertiary-container':     'var(--color-on-tertiary-container)',
        'error':                     'var(--color-error)',
        'on-error':                  'var(--color-on-error)',
        'error-container':           'var(--color-error-container)',
        'on-error-container':        'var(--color-on-error-container)',
        'primary-fixed':             'var(--color-primary-fixed)',
        'primary-fixed-dim':         'var(--color-primary-fixed-dim)',
        'on-primary-fixed':          'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant':  'var(--color-on-primary-fixed-variant)',
        'background':                'var(--color-background)',
        'on-background':             'var(--color-on-background)',
        'surface-variant':           'var(--color-surface-variant)',
      },
      fontFamily: {
        'display-lg':         ['IBM Plex Sans', 'sans-serif'],
        'headline-lg':        ['IBM Plex Sans', 'sans-serif'],
        'headline-md':        ['IBM Plex Sans', 'sans-serif'],
        'headline-lg-mobile': ['IBM Plex Sans', 'sans-serif'],
        'body-lg':            ['IBM Plex Sans', 'sans-serif'],
        'body-md':            ['IBM Plex Sans', 'sans-serif'],
        'label-caps':         ['JetBrains Mono', 'monospace'],
        'data-mono':          ['JetBrains Mono', 'monospace'],
        sans:                 ['IBM Plex Sans', 'sans-serif'],
        mono:                 ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg':         ['40px', { lineHeight: '1.1', fontWeight: '600', letterSpacing: '-0.02em' }],
        'headline-lg':        ['32px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md':        ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg':            ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps':         ['12px', { lineHeight: '1.0', fontWeight: '500', letterSpacing: '1.5px' }],
        'data-mono':          ['14px', { lineHeight: '1.4', fontWeight: '400', letterSpacing: '0.5px' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm':      '0.25rem',
        'md':      '0.75rem',
        'lg':      '0.5rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      spacing: {
        'xs':              '8px',
        'sm':              '12px',
        'md':              '24px',
        'lg':              '48px',
        'xl':              '80px',
        'gutter':          '24px',
        'margin-mobile':   '16px',
        'margin-desktop':  '40px',
        'base':            '4px',
      },
      boxShadow: {
        'tactical':    '4px 4px 0px 0px rgba(10,9,8,1)',
        'tactical-sm': '2px 2px 0px 0px rgba(10,9,8,1)',
        'tactical-lg': '6px 6px 0px 0px rgba(10,9,8,1)',
        'ambient':     '0 10px 30px -5px rgba(0,0,0,0.5)',
        'inset-press': 'inset 3px 3px 0px 0px rgba(0,0,0,0.5)',
      },
      animation: {
        'pulse-subtle':  'pulse 3s ease-in-out infinite',
        'fade-in':       'fadeIn var(--duration-page) var(--ease-page)',
        'slide-up':      'slideUp var(--duration-page) var(--ease-page)',
        'mic-pulse':     'micPulse 1s ease-in-out infinite',
      },
      transitionDuration: {
        'micro': 'var(--duration-micro)',
        'component': 'var(--duration-component)',
        'page': 'var(--duration-page)',
      },
      transitionTimingFunction: {
        'micro': 'var(--ease-micro)',
        'component': 'var(--ease-component)',
        'page': 'var(--ease-page)',
      },
      keyframes: {
        fadeIn: {
          '0%':   { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%':   { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        micPulse: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%':      { transform: 'scale(1.2)', opacity: '0.7' },
        },
      },
    },
  },
  plugins: [],
}
